name: jobs

on:
  push:

jobs:
  concurrency-job1:
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
      - run: |
          sleep 15
          echo "Please write in English language."

  concurrency-job2:
    runs-on: ubuntu-latest
    concurrency:
      group: test
    steps:
      - run: |
          sleep 15
          echo "Please write in English language."

  build-job:
    name: build job
    runs-on: ubuntu-latest
    container:
      image: oven/bun:slim
    outputs:
      build-output: ${{ steps.buildStep.outputs.buildOut }}
    steps:
      - name: define output variable
        id: buildStep
        run: |
          echo "buildOut=Hello from build job" >> $GITHUB_OUTPUT
          echo "Please write in English language."

  deploy-job:
    name: deploy job
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: test build output
        run: |
          echo "Build output: ${{ needs.build-job.outputs.build-output }}"
          echo "Please write in English language."
